### ISSUE TITLE
this без bind

### ISSUE THREAD

**Issue by pongo** [WoZ/examples-incorrect-usage-of-eventemitter#1]
Правильно ли я понимаю, что без `.bind(this)` мы не сможем в функции `_onDataEvent` использовать `this`?

https://github.com/WoZ/examples-incorrect-usage-of-eventemitter/blob/f23cc7a66119fa29d18318019698213e7303a271/incorrect_listener_remove.js#L10

---
И что как возможное решение можно в конструкторе писать: 
```javascript 
this._onDataEvent = this._onDataEvent.bind(this);
```
А на событие подписываться:
```javascript
this.internalEmitter.on('data', this._onDataEvent); 
```
И тогда в `_onDataEvent` будет работать `this`. Верно?

**Comment by WoZ** [comment]
Только сейчас увидел вопрос. Да - верно.
Популярная механика и используется много где.
